defaults: [paths]

seed: 42
device: "cuda"

window:
  size:            6
  input_windows:   2
  predict_windows: 1

pretrain:
  batch_size:   128
  num_epochs:   100
  lr:           1.0e-3
  patience:     15
  scheduler: {step_size: 20, gamma: 0.1}
