defaults:
  - global

pretrain:
  batch_size:    128
  num_epochs:    150
  lr:            1e-3
  weight_decay:  1e-5
  patience:      25
  scheduler:
    patience: 10
    factor:   0.5
    min_lr:   1e-6