defaults: [paths]

seed: 42
device: "cuda"

window_size: 6

test:
  batch_size:     32
  lr:             1.0e-3
  num_epochs:     20
  patience:       5
  unfreeze_ratio: 0.30
  scheduler: {step_size: 10, gamma: 0.1}
