defaults:
  - global

test:
  batch_size:     32
  lr:             1e-3
  num_epochs:     50
  patience:       5
  unfreeze_ratio: 0.30
  scheduler:
    patience: 3
    factor:   0.5
    min_lr:   1e-6