defaults: [paths]

seed: 42
device: "cuda"

window:
  size:            6
  input_windows:   2
  predict_windows: 1

train:
  batch_size:     64
  num_epochs:     30
  lr:             1.0e-4
  patience:       10
  unfreeze_ratio: 0.50
  scheduler: {step_size: 10, gamma: 0.1}
